USE [master]
GO

/****** Object:  Database [FirmaSiparisApp]    Script Date: 11.03.2023 22:46:15 ******/
CREATE DATABASE [FirmaSiparisApp]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FirmaSiparisApp', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\FirmaSiparisApp.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FirmaSiparisApp_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\FirmaSiparisApp_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FirmaSiparisApp].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FirmaSiparisApp] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FirmaSiparisApp] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FirmaSiparisApp] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FirmaSiparisApp] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FirmaSiparisApp] SET ARITHABORT OFF 
GO

ALTER DATABASE [FirmaSiparisApp] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [FirmaSiparisApp] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FirmaSiparisApp] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FirmaSiparisApp] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FirmaSiparisApp] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FirmaSiparisApp] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FirmaSiparisApp] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FirmaSiparisApp] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FirmaSiparisApp] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FirmaSiparisApp] SET  ENABLE_BROKER 
GO

ALTER DATABASE [FirmaSiparisApp] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FirmaSiparisApp] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FirmaSiparisApp] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FirmaSiparisApp] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FirmaSiparisApp] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FirmaSiparisApp] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [FirmaSiparisApp] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FirmaSiparisApp] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [FirmaSiparisApp] SET  MULTI_USER 
GO

ALTER DATABASE [FirmaSiparisApp] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FirmaSiparisApp] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FirmaSiparisApp] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FirmaSiparisApp] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [FirmaSiparisApp] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FirmaSiparisApp] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [FirmaSiparisApp] SET QUERY_STORE = OFF
GO

ALTER DATABASE [FirmaSiparisApp] SET  READ_WRITE 
GO


